---
- set_fact:
    system_settings_locale: en_US.UTF-8

- name: check if locale exists
  shell: "locale -a | grep -i {{ system_settings_locale | regex_replace('-', '') | quote }}"
  register: found_locale
  changed_when: no
  failed_when: no

- name: create locale
  command: "localedef -i {{ system_settings_locale | regex_replace('(.*)\\..*', '\\1') | quote }} -f {{ system_settings_locale | regex_replace('.*\\.(.*)', '\\1') | quote }} {{ system_settings_locale | quote }}"
  when: found_locale.rc != 0
